name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check Node.js files
        run: |
          errors=0
          if [ ! -f package.json ]; then
            echo "Error: package.json file not found"
            errors=$((errors+1))
          fi
          if [ ! -f .eslintrc.js ]; then
            echo "Error: .eslintrc.js file not found"
            errors=$((errors+1))
          fi
          if [ ! -d src ]; then
            echo "Error: src directory not found"
            errors=$((errors+1))
          fi
          if [ $errors -gt 0 ]; then
            echo "Errors found, failing workflow"
            exit 1
          fi
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Run linters
        run: |
          if npm run -s | grep -q "^lint$"; then
            npm run lint
          else
            echo "Lint script not found, skipping linting"
          fi

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          args: >
            -Dsonar.organization=saibhargav2001
            -Dsonar.projectKey=Saibhargav2001_SampleWebapp
